### ISSUE TITLE
Conditional tab "when the form Element" is not showing any option

### ISSUE THREAD

**Issue by mayankhpr** [dmenne/custom-radio#1]
![image](https://user-images.githubusercontent.com/30601917/102173441-fbfb3f80-3e68-11eb-9366-6636f4b4ecff.png)

**Comment by mayankhpr** [comment]
![image](https://user-images.githubusercontent.com/30601917/102173489-19c8a480-3e69-11eb-9f6b-0e652056b683.png)

**Comment by dmenne** [comment]
Sorry, I do no longer use Formio.
